import { useState, type ReactNode } from 'react';
import { CALIBER, CATS, ORG_TREE, ORG_ALLK, MET_DEFS, MET_DEFAULT, SORT_LABEL, SHIP_TYPE } from '../../data/self/catalog';
import { PERIOD } from '../../data/self/queryEngine';
import type { QueryController } from '../../hooks/self/useQuery';
import type { Period } from '../../data/self/types';
export function QueryIcon({ kind = 'grid' }: { kind?: string }) {
  const paths = { grid: 'M3 4h18v16H3z M3 10h18 M9 10v10 M15 10v10', search: 'M16 16l5 5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0', layers: 'M12 2L2 7l10 5 10-5-10-5z M2 17l10 5 10-5 M2 12l10 5 10-5', chart:'M3 17l6-6 4 4 8-8', calendar:'M3 4h18v18H3z M16 2v4 M8 2v4 M3 10h18', settings:'M4 21v-7 M4 10V3 M12 21v-9 M12 8V3 M20 21v-5 M20 12V3 M1 14h6 M9 8h6 M17 16h6' };
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d={paths[kind] || paths.grid}/></svg>;
}
function FilterCard({ title, value, kind, children }: { title: string; value: string; kind?: string; children: ReactNode }) {
  const [open, setOpen] = useState(false);
  return <div className={`period-card ${open ? 'open' : ''}`}><button className="cfg-row period-head" type="button" aria-expanded={open} onClick={() => setOpen(!open)}><span className="cfg-ic"><QueryIcon kind={kind}/></span><span className="cfg-label">{title}</span><span className="cfg-val">{value}</span><span className="cfg-chev">›</span></button><div className="period-pop">{children}</div></div>;
}
export function MetricsOptions({ selected, onChange, max }: { selected: Record<string,boolean>; onChange: (next: Record<string,boolean>)=>void; max?: number }) {
  const [search, setSearch] = useState('');
  const groups = [...new Set(MET_DEFS.map(m => m.g))];
  return <><div className="met-search"><QueryIcon kind="search"/><input aria-label="搜索指标名称" placeholder="搜索指标名称" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="met-tools"><button className="met-link" onClick={()=>onChange(Object.fromEntries(MET_DEFS.map((m,i)=>[m.k,!max || i<max])))}>全选</button> · <button className="met-link" onClick={()=>onChange({})}>清空</button> · <button className="met-link" onClick={()=>onChange(Object.fromEntries(Object.entries(MET_DEFAULT).map(([k,v])=>[k,!!v])))}>恢复默认</button></div><div className="met-tree">{groups.map(group => {const metrics=MET_DEFS.filter(m=>m.g===group&&m.n.includes(search));if(!metrics.length)return null;return <div className="met-group" key={group}><div className="met-ghead"><b>{group}</b></div>{metrics.map(m=><label className="met-item" key={m.k}><input type="checkbox" checked={!!selected[m.k]} disabled={!!max&&!selected[m.k]&&Object.values(selected).filter(Boolean).length>=max} onChange={e=>onChange({...selected,[m.k]:e.target.checked})}/><span title={m.d}>{m.n}</span></label>)}</div>;})}</div></>;
}
export function QuerySidebar({ query }: { query: QueryController }) {
  const { config,patch,engine }=query;
  const [search,setSearch]=useState(''), [onlySelected,setOnlySelected]=useState(false), [gran,setGran]=useState('month'), [more,setMore]=useState(false);
  const [collapsed,setCollapsed]=useState<Record<string,boolean>>({});
  const selectOrg=(keys:string[],checked:boolean)=>patch({orgSel:{...config.orgSel,...Object.fromEntries(keys.map(k=>[k,checked]))}});
  const selected=engine.orgSelArr();
  const periods:Period[] = gran==='month'?Array.from({length:more?32:8},(_,i)=>{const d=new Date(2026,7-i,1);return {y:d.getFullYear(),m0:d.getMonth()+1,m1:d.getMonth()+1};}):gran==='quarter'?Array.from({length:8},(_,i)=>{const d=new Date(2026,6-i*3,1);return {y:d.getFullYear(),m0:d.getMonth()+1,m1:d.getMonth()+3};}):Array.from({length:5},(_,i)=>({y:2026-i,m0:1,m1:12}));
  return <div className="panel-view"><div className="cfg-list">
    <FilterCard title="组织范围" value={engine.orgHeadText()}><div className="org-search"><QueryIcon kind="search"/><input placeholder="搜索业务板块 / 航运公司" aria-label="搜索业务板块或航运公司" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="org-ops"><button onClick={()=>selectOrg(ORG_ALLK(),true)}>全选</button> · <button onClick={()=>selectOrg(ORG_ALLK(),false)}>清空</button> · <button onClick={()=>setOnlySelected(!onlySelected)}>{onlySelected?'查看全部':'仅看已选'}</button></div><div className="org-tree"><label className="ot-row"><input type="checkbox" checked={selected.length===ORG_ALLK().length} onChange={e=>selectOrg(ORG_ALLK(),e.target.checked)}/>{ORG_TREE.name}</label>{ORG_TREE.children.map(g=>{const children=g.children.filter(l=>(!search||l.name.includes(search)||g.name.includes(search))&&(!onlySelected||config.orgSel[l.k]));if(!children.length)return null;return <div key={g.k}><div className="ot-row" style={{paddingLeft:12}}><button className="ot-chev" onClick={()=>setCollapsed({...collapsed,[g.k]:!collapsed[g.k]})}>{collapsed[g.k]?'▸':'▾'}</button><input aria-label={g.name} type="checkbox" checked={g.children.every(l=>config.orgSel[l.k])} onChange={e=>selectOrg(g.children.map(l=>l.k),e.target.checked)}/><span>{g.name}</span></div>{!collapsed[g.k]&&children.map(l=><label className="ot-row" style={{paddingLeft:36}} key={l.k}><input type="checkbox" checked={!!config.orgSel[l.k]} onChange={e=>selectOrg([l.k],e.target.checked)}/>{l.name}</label>)}</div>;})}</div></FilterCard>
    <FilterCard title="统计周期" value={PERIOD(config.period).label} kind="calendar"><div className="seg3">{[['year','年度'],['quarter','季度'],['month','月份']].map(([k,label])=><button className={gran===k?'active':''} key={k} onClick={()=>setGran(k)}>{label}</button>)}</div><div className="cur-line">当前选择：<b>{PERIOD(config.period).label}</b></div><div className="pchip-row">{periods.map(p=><button className={`pchip ${JSON.stringify(config.period)===JSON.stringify(p)?'active':''}`} key={`${p.y}-${p.m0}`} onClick={()=>patch({period:p})}>{PERIOD(p).label}</button>)}{gran==='month'&&<button className="pchip more" onClick={()=>setMore(!more)}>{more?'收起':'更多月份'}</button>}</div></FilterCard>
    <FilterCard title="统计口径" value={CALIBER[config.caliber].label} kind="settings"><div className="cal-chips">{Object.entries(CALIBER).map(([key,value])=><button className={`cal-chip ${config.caliber===key?'active':''}`} key={key} onClick={()=>patch({caliber:key})}>{value.label}</button>)}</div></FilterCard>
    <FilterCard title="船型" value={SHIP_TYPE[config.ship].label} kind="layers"><div className="cfg-hint">用于筛选当前查询的船型范围。</div><div className="cal-chips">{Object.entries(SHIP_TYPE).map(([key,value])=><button className={`cal-chip ${config.ship===key?'active':''}`} disabled={engine.orgUnits().length===1&&config.ship!==key} key={key} onClick={()=>patch({ship:key})}>{value.label}</button>)}</div><label><input type="checkbox" checked={config.dims.includes('ship')} onChange={e=>patch({dims:e.target.checked?[...config.dims,'ship']:config.dims.filter(d=>d!=='ship')})}/>按船型拆分明细</label></FilterCard>
    <FilterCard title="更多配置" value="维度 / 指标 / 排序" kind="settings"><details className="more-card" open><summary className="mc-head"><b>分析维度</b><span className="mc-cnt">已选 {config.dims.length} 项</span></summary><div className="dim-chips">{[['unit','业务单位'],['cargo','货类'],['route','航线'],['month','月份'],['ship','船型']].map(([key,label])=><button className={`dim-chip ${config.dims.includes(key)?'active':''}`} key={key} onClick={()=>patch({dims:config.dims.includes(key)?config.dims.filter(d=>d!==key):[...config.dims,key]})}>{label}</button>)}</div></details><details className="more-card"><summary className="mc-head"><b>指标选择</b><span className="mc-cnt">已选 {Object.values(config.metrics).filter(Boolean).length} 项</span></summary><MetricsOptions selected={config.metrics} onChange={metrics=>patch({metrics})}/></details><details className="more-card"><summary className="mc-head"><b>排序设置</b></summary><div className="sort-line"><select aria-label="排序字段" value={config.sortKey} onChange={e=>patch({sortKey:e.target.value as typeof config.sortKey})}>{Object.entries(SORT_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><div className="sort-seg">{(['asc','desc'] as const).map(k=><button className={config.sortDir===k?'active':''} key={k} onClick={()=>patch({sortDir:k})}>{k==='asc'?'升序':'降序'}</button>)}</div></div></details><details className="more-card"><summary className="mc-head"><b>货类筛选</b></summary><div className="cal-chips">{[{k:'all',name:'全部'},...CATS].map(c=><button className={`cal-chip ${config.cargo===c.k?'active':''}`} key={c.k} onClick={()=>patch({cargo:c.k})}>{c.name}</button>)}</div></details></FilterCard>
  </div></div>;
}
